### ISSUE TITLE
Add EpiViruSurf to SchemaSpy showcase?

### ISSUE THREAD

**Issue by npetzall** [DEIB-GECO/EpiSurf#1]
Hi, 

I'm one of the maintainers of SchemaSpy, I'm thrilled that you used our project in your research. We think it's really cool and would like to use the output for EpiViruSurf to showcase SchemaSpy (in addition to our current sample). Do we have your permission to do so?

**Comment by sunbrn** [comment]
Dear @npetzall,
apologies for the delayed response. 
Thank you for your interest in our project. Yes, please feel free to use EpiViruSurf for showcasing SchemaSpy!
You have our permission!
Best, the EpiViruSurf team.
